"""
Fake identity data for 100+ countries.
Each entry: name, phone_code, phone_len, cities, streets, first, last
"""

import random


FAKE_DATA = {
    # ───────── NORTH AMERICA ─────────
    "US": {"name": "United States", "phone_code": "+1", "phone_len": 10,
        "cities": [("New York", "NY", "10001"), ("Los Angeles", "CA", "90001"),
                   ("Chicago", "IL", "60601"), ("Houston", "TX", "77001"),
                   ("Phoenix", "AZ", "85001"), ("Miami", "FL", "33101"),
                   ("Seattle", "WA", "98101"), ("Boston", "MA", "02101"),
                   ("Denver", "CO", "80201"), ("Atlanta", "GA", "30301")],
        "streets": ["Main St", "Oak Ave", "Pine Rd", "Maple Dr", "Cedar Ln",
                    "Elm St", "Broadway", "Sunset Blvd", "First Street", "Park Ave"],
        "first": ["John", "Jane", "Michael", "Sarah", "David", "Emma", "James",
                  "Olivia", "Robert", "Linda", "Martha", "William"],
        "last": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia",
                 "Miller", "Davis", "Wilson", "Anderson", "Frazier"]},
    "CA": {"name": "Canada", "phone_code": "+1", "phone_len": 10,
        "cities": [("Toronto", "ON", "M5V 2H1"), ("Vancouver", "BC", "V6Z 2E6"),
                   ("Montreal", "QC", "H2Y 1J1"), ("Calgary", "AB", "T2P 1J9"),
                   ("Ottawa", "ON", "K1A 0A6"), ("Edmonton", "AB", "T5J 0N3")],
        "streets": ["Main St", "Queen St", "King St", "Bay St", "Yonge St", "Bloor St"],
        "first": ["Liam", "Noah", "Oliver", "Elijah", "William", "James", "Benjamin", "Lucas"],
        "last": ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Tremblay", "Roy"]},
    "MX": {"name": "Mexico", "phone_code": "+52", "phone_len": 10,
        "cities": [("Ciudad de México", "CDMX", "01000"), ("Guadalajara", "Jalisco", "44100"),
                   ("Monterrey", "NL", "64000"), ("Puebla", "PUE", "72000"), ("Tijuana", "BC", "22000")],
        "streets": ["Avenida Reforma", "Calle Madero", "Avenida Juárez", "Calle 5 de Mayo"],
        "first": ["José", "Juan", "Miguel", "Luis", "Carlos", "Jesús", "Alejandro", "Pedro"],
        "last": ["Hernández", "García", "Martínez", "López", "González", "Pérez", "Rodríguez", "Sánchez"]},

    # ───────── SOUTH AMERICA ─────────
    "BR": {"name": "Brazil", "phone_code": "+55", "phone_len": 11,
        "cities": [("São Paulo", "SP", "01310-100"), ("Rio de Janeiro", "RJ", "20040-020"),
                   ("Brasília", "DF", "70040-010"), ("Salvador", "BA", "40000-000"),
                   ("Fortaleza", "CE", "60000-000"), ("Belo Horizonte", "MG", "30140-071")],
        "streets": ["Avenida Paulista", "Avenida Brasil", "Rua Augusta", "Rua das Flores"],
        "first": ["João", "Pedro", "Lucas", "Gabriel", "Rafael", "Mateus", "Bruno", "Felipe"],
        "last": ["Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Almeida", "Costa"]},
    "AR": {"name": "Argentina", "phone_code": "+54", "phone_len": 10,
        "cities": [("Buenos Aires", "C", "1000"), ("Córdoba", "X", "5000"),
                   ("Rosario", "S", "2000"), ("Mendoza", "M", "5500")],
        "streets": ["Avenida Corrientes", "Avenida 9 de Julio", "Calle Florida"],
        "first": ["Juan", "Santiago", "Matías", "Lucas", "Nicolás", "Facundo", "Tomás", "Agustín"],
        "last": ["González", "Rodríguez", "Fernández", "López", "Martínez", "Gómez", "Pérez", "Romero"]},
    "CL": {"name": "Chile", "phone_code": "+56", "phone_len": 9,
        "cities": [("Santiago", "RM", "8320000"), ("Valparaíso", "VS", "2340000"),
                   ("Concepción", "BI", "4030000")],
        "streets": ["Avenida Providencia", "Avenida Libertador", "Calle Ahumada"],
        "first": ["Matías", "Benjamín", "Vicente", "Sebastián", "Tomás", "Diego", "Ignacio"],
        "last": ["González", "Muñoz", "Rojas", "Díaz", "Pérez", "Soto", "Contreras"]},
    "CO": {"name": "Colombia", "phone_code": "+57", "phone_len": 10,
        "cities": [("Bogotá", "DC", "110111"), ("Medellín", "ANT", "050001"),
                   ("Cali", "VAC", "760001"), ("Barranquilla", "ATL", "080001")],
        "streets": ["Carrera 7", "Avenida El Dorado", "Calle 100"],
        "first": ["Santiago", "Sebastián", "Juan", "Andrés", "Felipe", "Diego", "Camilo"],
        "last": ["Rodríguez", "Gómez", "González", "Martínez", "García", "López", "Ramírez"]},
    "PE": {"name": "Peru", "phone_code": "+51", "phone_len": 9,
        "cities": [("Lima", "LIM", "15001"), ("Arequipa", "ARE", "04001"), ("Trujillo", "LAL", "13001")],
        "streets": ["Avenida Arequipa", "Avenida Larco", "Jirón de la Unión"],
        "first": ["Diego", "Sebastián", "Alejandro", "Gonzalo", "Rodrigo", "Matías"],
        "last": ["Quispe", "Mamani", "Huamán", "Flores", "García", "Rodríguez"]},
    "VE": {"name": "Venezuela", "phone_code": "+58", "phone_len": 10,
        "cities": [("Caracas", "DC", "1010"), ("Maracaibo", "Z", "4001"), ("Valencia", "G", "2001")],
        "streets": ["Avenida Bolívar", "Avenida Libertador", "Calle Real"],
        "first": ["José", "Carlos", "Luis", "Miguel", "Rafael", "Alejandro"],
        "last": ["González", "Rodríguez", "Pérez", "Hernández", "García"]},
    "EC": {"name": "Ecuador", "phone_code": "+593", "phone_len": 9,
        "cities": [("Quito", "P", "170150"), ("Guayaquil", "G", "090150")],
        "streets": ["Avenida Amazonas", "Avenida 9 de Octubre"],
        "first": ["Carlos", "Luis", "Jorge", "Andrés", "Diego"],
        "last": ["García", "Rodríguez", "Pérez", "Martínez", "López"]},
    "UY": {"name": "Uruguay", "phone_code": "+598", "phone_len": 8,
        "cities": [("Montevideo", "MO", "11000"), ("Salto", "SA", "50000")],
        "streets": ["Avenida 18 de Julio", "Calle Sarandí"],
        "first": ["Santiago", "Martín", "Federico", "Diego"],
        "last": ["Rodríguez", "Pérez", "Fernández", "González"]},
    "PY": {"name": "Paraguay", "phone_code": "+595", "phone_len": 9,
        "cities": [("Asunción", "ASU", "1001"), ("Ciudad del Este", "APA", "7000")],
        "streets": ["Avenida Mariscal López", "Calle Palma"],
        "first": ["Juan", "Carlos", "José", "Diego"],
        "last": ["González", "Rodríguez", "Martínez", "López"]},
    "BO": {"name": "Bolivia", "phone_code": "+591", "phone_len": 8,
        "cities": [("La Paz", "LP", "0001"), ("Santa Cruz", "SC", "0001")],
        "streets": ["Avenida 16 de Julio", "Calle Comercio"],
        "first": ["Juan", "Carlos", "Luis", "Diego"],
        "last": ["Mamani", "Quispe", "Flores", "García"]},

    # ───────── EUROPE ─────────
    "GB": {"name": "United Kingdom", "phone_code": "+44", "phone_len": 10,
        "cities": [("London", "ENG", "EC1A 1BB"), ("Birmingham", "ENG", "B1 1AA"),
                   ("Manchester", "ENG", "M1 1AE"), ("Glasgow", "SCT", "G1 1AA"),
                   ("Edinburgh", "SCT", "EH1 1YZ"), ("Liverpool", "ENG", "L1 1AA"),
                   ("Bristol", "ENG", "BS1 1AA"), ("Leeds", "ENG", "LS1 1AA")],
        "streets": ["High St", "Church St", "Queen St", "King St",
                    "Victoria Rd", "Oxford St", "Baker St", "Abbey Road"],
        "first": ["Oliver", "George", "Harry", "Jack", "Jacob", "Charlie",
                  "Thomas", "William", "James", "Henry"],
        "last": ["Smith", "Jones", "Williams", "Taylor", "Brown",
                 "Davies", "Wilson", "Evans", "Thomas", "Roberts"]},
    "IE": {"name": "Ireland", "phone_code": "+353", "phone_len": 9,
        "cities": [("Dublin", "D", "D02 Y006"), ("Cork", "CO", "T12 XY88"),
                   ("Galway", "G", "H91 AB12"), ("Limerick", "LK", "V94 XY88")],
        "streets": ["Grafton St", "O'Connell St", "Patrick St", "Dame St"],
        "first": ["Sean", "Patrick", "Conor", "Liam", "Ciaran", "Declan", "Jack", "Cillian"],
        "last": ["Murphy", "Kelly", "O'Brien", "Walsh", "Byrne", "Ryan", "O'Connor", "O'Sullivan"]},
    "DE": {"name": "Germany", "phone_code": "+49", "phone_len": 11,
        "cities": [("Berlin", "BE", "10115"), ("Hamburg", "HH", "20095"),
                   ("München", "BY", "80331"), ("Köln", "NW", "50667"),
                   ("Frankfurt", "HE", "60311"), ("Stuttgart", "BW", "70173"),
                   ("Düsseldorf", "NW", "40213"), ("Leipzig", "SN", "04103")],
        "streets": ["Hauptstraße", "Bahnhofstraße", "Schulstraße",
                    "Gartenstraße", "Lindenweg", "Goethestraße", "Schillerstraße"],
        "first": ["Lukas", "Maximilian", "Felix", "Jonas", "Leon", "Paul",
                  "Elias", "Niklas", "Alexander", "Moritz"],
        "last": ["Müller", "Schmidt", "Schneider", "Fischer", "Weber",
                 "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann"]},
    "FR": {"name": "France", "phone_code": "+33", "phone_len": 9,
        "cities": [("Paris", "IDF", "75001"), ("Marseille", "PACA", "13001"),
                   ("Lyon", "ARA", "69001"), ("Toulouse", "OCC", "31000"),
                   ("Nice", "PACA", "06000"), ("Bordeaux", "NAQ", "33000"),
                   ("Lille", "HDF", "59000"), ("Strasbourg", "GES", "67000")],
        "streets": ["Rue de la Paix", "Avenue Victor Hugo", "Rue Saint-Honoré",
                    "Boulevard Voltaire", "Avenue des Champs-Élysées", "Rue de Rivoli"],
        "first": ["Gabriel", "Louis", "Raphaël", "Jules", "Adam", "Maël",
                  "Lucas", "Hugo", "Arthur", "Léo"],
        "last": ["Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard",
                 "Petit", "Durand", "Leroy", "Moreau"]},
    "IT": {"name": "Italy", "phone_code": "+39", "phone_len": 10,
        "cities": [("Roma", "Lazio", "00100"), ("Milano", "Lombardia", "20100"),
                   ("Napoli", "Campania", "80100"), ("Torino", "Piemonte", "10100"),
                   ("Firenze", "Toscana", "50100"), ("Venezia", "Veneto", "30100")],
        "streets": ["Via Roma", "Via Garibaldi", "Via Dante", "Via Cavour"],
        "first": ["Leonardo", "Francesco", "Alessandro", "Lorenzo", "Mattia", "Andrea", "Marco", "Luca"],
        "last": ["Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci"]},
    "ES": {"name": "Spain", "phone_code": "+34", "phone_len": 9,
        "cities": [("Madrid", "Madrid", "28001"), ("Barcelona", "Cataluña", "08001"),
                   ("Valencia", "Valencia", "46001"), ("Sevilla", "Andalucía", "41001"),
                   ("Bilbao", "País Vasco", "48001"), ("Málaga", "Andalucía", "29001")],
        "streets": ["Calle Mayor", "Gran Vía", "Calle Real", "Avenida de la Constitución"],
        "first": ["Hugo", "Martín", "Pablo", "Alejandro", "Daniel", "Adrián", "Álvaro", "Javier"],
        "last": ["García", "Rodríguez", "González", "Fernández", "López", "Martínez", "Sánchez", "Pérez"]},
    "PT": {"name": "Portugal", "phone_code": "+351", "phone_len": 9,
        "cities": [("Lisboa", "Lisboa", "1100"), ("Porto", "Porto", "4000"),
                   ("Coimbra", "Coimbra", "3000"), ("Braga", "Braga", "4700")],
        "streets": ["Rua Augusta", "Avenida da Liberdade", "Rua do Ouro", "Avenida da República"],
        "first": ["João", "Miguel", "Pedro", "Rui", "Tiago", "Diogo", "Francisco", "Gonçalo"],
        "last": ["Silva", "Santos", "Ferreira", "Pereira", "Oliveira", "Costa", "Rodrigues", "Martins"]},
    "NL": {"name": "Netherlands", "phone_code": "+31", "phone_len": 9,
        "cities": [("Amsterdam", "NH", "1011"), ("Rotterdam", "ZH", "3011"),
                   ("Den Haag", "ZH", "2511"), ("Utrecht", "UT", "3511")],
        "streets": ["Kerkstraat", "Hoofdstraat", "Molenstraat", "Nieuwstraat"],
        "first": ["Daan", "Sem", "Lucas", "Milan", "Levi", "Luuk", "Finn", "Jesse"],
        "last": ["De Jong", "Jansen", "De Vries", "Van den Berg", "Van Dijk", "Bakker", "Visser", "De Boer"]},
    "BE": {"name": "Belgium", "phone_code": "+32", "phone_len": 9,
        "cities": [("Brussel", "BRU", "1000"), ("Antwerpen", "VAN", "2000"),
                   ("Gent", "OVL", "9000"), ("Brugge", "WVL", "8000")],
        "streets": ["Grote Markt", "Nieuwstraat", "Kerkstraat", "Meir"],
        "first": ["Lucas", "Arthur", "Louis", "Jules", "Noah", "Victor", "Finn", "Wout"],
        "last": ["Peeters", "Janssens", "Maes", "Jacobs", "Mertens", "Willems", "Claes", "Goossens"]},
    "CH": {"name": "Switzerland", "phone_code": "+41", "phone_len": 9,
        "cities": [("Zürich", "ZH", "8001"), ("Genève", "GE", "1201"),
                   ("Basel", "BS", "4001"), ("Bern", "BE", "3000"), ("Lausanne", "VD", "1000")],
        "streets": ["Bahnhofstrasse", "Hauptstrasse", "Rue du Rhône", "Freie Strasse"],
        "first": ["Noah", "Liam", "Luca", "Leon", "Elias", "Julian", "Nicolas", "David"],
        "last": ["Müller", "Meier", "Schmid", "Keller", "Weber", "Huber", "Schneider", "Moser"]},
    "AT": {"name": "Austria", "phone_code": "+43", "phone_len": 10,
        "cities": [("Wien", "Wien", "1010"), ("Graz", "Steiermark", "8010"),
                   ("Linz", "OÖ", "4020"), ("Salzburg", "Sbg", "5020")],
        "streets": ["Mariahilfer Straße", "Ringstraße", "Kärntner Straße", "Getreidegasse"],
        "first": ["Lukas", "Maximilian", "Jakob", "Elias", "Tobias", "Simon", "David", "Paul"],
        "last": ["Gruber", "Huber", "Bauer", "Wagner", "Müller", "Pichler", "Steiner", "Moser"]},
    "SE": {"name": "Sweden", "phone_code": "+46", "phone_len": 9,
        "cities": [("Stockholm", "AB", "111 20"), ("Göteborg", "VG", "411 01"),
                   ("Malmö", "SN", "211 20"), ("Uppsala", "C", "751 20")],
        "streets": ["Vasagatan", "Kungsgatan", "Sveavägen", "Drottninggatan"],
        "first": ["William", "Lucas", "Erik", "Liam", "Noah", "Oscar", "Hugo", "Axel"],
        "last": ["Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson"]},
    "NO": {"name": "Norway", "phone_code": "+47", "phone_len": 8,
        "cities": [("Oslo", "03", "0154"), ("Bergen", "12", "5003"), ("Trondheim", "16", "7004")],
        "streets": ["Karl Johans gate", "Storgata", "Kirkegata"],
        "first": ["Jakob", "Oliver", "Emil", "Noah", "Lucas", "Filip", "Magnus", "Henrik"],
        "last": ["Hansen", "Johansen", "Olsen", "Larsen", "Andersen", "Nilsen", "Berg", "Haugen"]},
    "DK": {"name": "Denmark", "phone_code": "+45", "phone_len": 8,
        "cities": [("København", "84", "1457"), ("Aarhus", "82", "8000"), ("Odense", "83", "5000")],
        "streets": ["Strøget", "Nørrebrogade", "Vesterbrogade", "Amagerbrogade"],
        "first": ["William", "Oscar", "Noah", "Lucas", "Malthe", "Alfred", "Frederik", "Valdemar"],
        "last": ["Nielsen", "Jensen", "Hansen", "Pedersen", "Andersen", "Christensen", "Larsen", "Sørensen"]},
    "FI": {"name": "Finland", "phone_code": "+358", "phone_len": 9,
        "cities": [("Helsinki", "18", "00100"), ("Espoo", "18", "02100"), ("Tampere", "11", "33100")],
        "streets": ["Mannerheimintie", "Aleksanterinkatu", "Kauppakatu"],
        "first": ["Elias", "Oliver", "Väinö", "Eino", "Leo", "Emil", "Onni"],
        "last": ["Korhonen", "Virtanen", "Mäkinen", "Nieminen", "Hämäläinen", "Laine", "Heikkinen"]},
    "IS": {"name": "Iceland", "phone_code": "+354", "phone_len": 7,
        "cities": [("Reykjavík", "1", "101"), ("Akureyri", "6", "600")],
        "streets": ["Laugavegur", "Skólavörðustígur"],
        "first": ["Jón", "Sigurður", "Guðmundur", "Ólafur"],
        "last": ["Jónsson", "Sigurðsson", "Guðmundsson", "Ólafsson"]},
    "PL": {"name": "Poland", "phone_code": "+48", "phone_len": 9,
        "cities": [("Warszawa", "MZ", "00-001"), ("Kraków", "MA", "30-001"),
                   ("Gdańsk", "PM", "80-001"), ("Wrocław", "DS", "50-001"), ("Poznań", "WP", "60-001")],
        "streets": ["ul. Marszałkowska", "ul. Nowy Świat", "ul. Krakowskie Przedmieście", "ul. Piotrkowska"],
        "first": ["Jakub", "Szymon", "Jan", "Antoni", "Filip", "Mikołaj", "Wojciech", "Adam"],
        "last": ["Nowak", "Kowalski", "Wiśniewski", "Wójcik", "Kowalczyk", "Kamiński", "Lewandowski", "Zieliński"]},
    "CZ": {"name": "Czech Republic", "phone_code": "+420", "phone_len": 9,
        "cities": [("Praha", "PHA", "110 00"), ("Brno", "JHM", "602 00"),
                   ("Ostrava", "MSK", "702 00"), ("Plzeň", "PLK", "301 00")],
        "streets": ["Václavské náměstí", "Karlova", "Nádražní", "Hlavní"],
        "first": ["Jakub", "Jan", "Tomáš", "Adam", "Matěj", "Vojtěch", "Filip", "Ondřej"],
        "last": ["Novák", "Svoboda", "Novotný", "Dvořák", "Černý", "Procházka", "Kučera", "Veselý"]},
    "SK": {"name": "Slovakia", "phone_code": "+421", "phone_len": 9,
        "cities": [("Bratislava", "BA", "811 01"), ("Košice", "KE", "040 01")],
        "streets": ["Hlavná ulica", "Obchodná ulica"],
        "first": ["Jakub", "Samuel", "Tomáš", "Martin", "Adam"],
        "last": ["Horváth", "Kováč", "Varga", "Tóth", "Nagy"]},
    "HU": {"name": "Hungary", "phone_code": "+36", "phone_len": 9,
        "cities": [("Budapest", "BU", "1051"), ("Debrecen", "HB", "4024"), ("Szeged", "CS", "6720")],
        "streets": ["Váci utca", "Andrássy út", "Kossuth Lajos utca"],
        "first": ["Bence", "Máté", "Levente", "Dominik", "Marcell", "Ádám", "Dániel", "Dávid"],
        "last": ["Nagy", "Kovács", "Tóth", "Szabó", "Horváth", "Varga", "Kiss", "Molnár"]},
    "RO": {"name": "Romania", "phone_code": "+40", "phone_len": 9,
        "cities": [("București", "B", "010011"), ("Cluj-Napoca", "CJ", "400001"),
                   ("Timișoara", "TM", "300001"), ("Iași", "IS", "700001")],
        "streets": ["Calea Victoriei", "Bulevardul Unirii", "Strada Lipscani"],
        "first": ["Andrei", "Alexandru", "Mihai", "Ștefan", "Gabriel", "David", "Ion", "Vlad"],
        "last": ["Popescu", "Ionescu", "Popa", "Stan", "Dumitru", "Stoica", "Gheorghe", "Matei"]},
    "BG": {"name": "Bulgaria", "phone_code": "+359", "phone_len": 9,
        "cities": [("Sofia", "S", "1000"), ("Plovdiv", "PB", "4000")],
        "streets": ["бул. Витоша", "бул. Цар Освободител"],
        "first": ["Georgi", "Ivan", "Dimitar", "Nikolay"],
        "last": ["Ivanov", "Petrov", "Dimitrov", "Georgiev"]},
    "GR": {"name": "Greece", "phone_code": "+30", "phone_len": 10,
        "cities": [("Αθήνα", "ATT", "10431"), ("Θεσσαλονίκη", "CM", "54001"), ("Πάτρα", "WC", "26221")],
        "streets": ["Ερμού", "Πανεπιστημίου", "Σταδίου"],
        "first": ["Γιώργος", "Δημήτρης", "Νίκος", "Γιάννης", "Κώστας", "Παναγιώτης"],
        "last": ["Παπαδόπουλος", "Γεωργίου", "Δημητρίου", "Νικολάου", "Αντωνίου", "Μακρής"]},
    "HR": {"name": "Croatia", "phone_code": "+385", "phone_len": 9,
        "cities": [("Zagreb", "ZG", "10000"), ("Split", "ST", "21000")],
        "streets": ["Ilica", "Vukovarska"],
        "first": ["Ivan", "Marko", "Luka", "David"],
        "last": ["Horvat", "Kovačević", "Babić", "Marić"]},
    "SI": {"name": "Slovenia", "phone_code": "+386", "phone_len": 8,
        "cities": [("Ljubljana", "LJ", "1000"), ("Maribor", "MB", "2000")],
        "streets": ["Slovenska cesta", "Prešernova cesta"],
        "first": ["Luka", "Jan", "Žan", "Nejc"],
        "last": ["Novak", "Horvat", "Kovačič", "Zupan"]},
    "RS": {"name": "Serbia", "phone_code": "+381", "phone_len": 9,
        "cities": [("Beograd", "BG", "11000"), ("Novi Sad", "VO", "21000")],
        "streets": ["Knez Mihailova", "Bulevar kralja Aleksandra"],
        "first": ["Marko", "Nikola", "Luka", "Stefan"],
        "last": ["Jovanović", "Petrović", "Nikolić", "Marković"]},
    "UA": {"name": "Ukraine", "phone_code": "+380", "phone_len": 9,
        "cities": [("Київ", "KV", "01001"), ("Харків", "KH", "61001"), ("Одеса", "OD", "65001")],
        "streets": ["Хрещатик", "вул. Сагайдачного", "вул. Дерибасівська"],
        "first": ["Олександр", "Андрій", "Максим", "Іван", "Дмитро", "Сергій"],
        "last": ["Шевченко", "Коваленко", "Бондаренко", "Ткаченко", "Кравченко", "Мельник"]},
    "RU": {"name": "Russia", "phone_code": "+7", "phone_len": 10,
        "cities": [("Москва", "MOW", "101000"), ("Санкт-Петербург", "SPE", "190000"),
                   ("Новосибирск", "NVS", "630000"), ("Екатеринбург", "SVE", "620000")],
        "streets": ["ул. Тверская", "Невский проспект", "ул. Арбат", "ул. Ленина"],
        "first": ["Александр", "Дмитрий", "Иван", "Максим", "Сергей", "Андрей", "Николай", "Михаил"],
        "last": ["Иванов", "Смирнов", "Кузнецов", "Попов", "Соколов", "Лебедев", "Козлов", "Новиков"]},
    "BY": {"name": "Belarus", "phone_code": "+375", "phone_len": 9,
        "cities": [("Минск", "MI", "220000"), ("Гомель", "HO", "246000")],
        "streets": ["пр. Независимости", "ул. Ленина"],
        "first": ["Александр", "Дмитрий", "Сергей", "Андрей"],
        "last": ["Иванов", "Петров", "Сидоров", "Козлов"]},
    "MD": {"name": "Moldova", "phone_code": "+373", "phone_len": 8,
        "cities": [("Chișinău", "CU", "MD-2000"), ("Bălți", "BA", "MD-3100")],
        "streets": ["Bulevardul Ștefan cel Mare", "Strada Alexandru cel Bun"],
        "first": ["Andrei", "Ion", "Vasile", "Nicolae"],
        "last": ["Popescu", "Ionescu", "Rusu", "Ceban"]},
    "LT": {"name": "Lithuania", "phone_code": "+370", "phone_len": 8,
        "cities": [("Vilnius", "VL", "LT-01001"), ("Kaunas", "KU", "LT-44001")],
        "streets": ["Gedimino prospektas", "Vilniaus gatvė"],
        "first": ["Lukas", "Matas", "Domantas", "Tomas"],
        "last": ["Kazlauskas", "Jankauskas", "Petrauskas", "Stankevičius"]},
    "LV": {"name": "Latvia", "phone_code": "+371", "phone_len": 8,
        "cities": [("Rīga", "RIX", "LV-1001"), ("Daugavpils", "DGV", "LV-5401")],
        "streets": ["Brīvības iela", "Gertrūdes iela"],
        "first": ["Jānis", "Andris", "Māris", "Kārlis"],
        "last": ["Bērziņš", "Ozols", "Kalniņš", "Jansons"]},
    "EE": {"name": "Estonia", "phone_code": "+372", "phone_len": 8,
        "cities": [("Tallinn", "HA", "10111"), ("Tartu", "TA", "50089")],
        "streets": ["Narva maantee", "Viru tänav"],
        "first": ["Marko", "Jaan", "Andres", "Peeter"],
        "last": ["Tamm", "Saar", "Sepp", "Mägi"]},
    "LU": {"name": "Luxembourg", "phone_code": "+352", "phone_len": 9,
        "cities": [("Luxembourg", "LU", "L-1111"), ("Esch-sur-Alzette", "ES", "L-4001")],
        "streets": ["Grand-Rue", "Avenue de la Liberté"],
        "first": ["Luca", "Tom", "Max", "Ben"],
        "last": ["Schmit", "Weber", "Hoffmann", "Muller"]},
    "MT": {"name": "Malta", "phone_code": "+356", "phone_len": 8,
        "cities": [("Valletta", "VLT", "VLT 1111"), ("Sliema", "SLM", "SLM 1000")],
        "streets": ["Triq ir-Repubblika", "Triq il-Kbira"],
        "first": ["John", "Mark", "David", "Paul"],
        "last": ["Borg", "Camilleri", "Vella", "Farrugia"]},

    # ───────── MIDDLE EAST ─────────
    "TR": {"name": "Turkey", "phone_code": "+90", "phone_len": 10,
        "cities": [("İstanbul", "İstanbul", "34000"), ("Ankara", "Ankara", "06000"),
                   ("İzmir", "İzmir", "35000"), ("Bursa", "Bursa", "16000")],
        "streets": ["Atatürk Caddesi", "İstiklal Caddesi", "Cumhuriyet Caddesi"],
        "first": ["Yusuf", "Miraç", "Mustafa", "Ahmet", "Mehmet", "Emir", "Ali", "Hüseyin"],
        "last": ["Yılmaz", "Kaya", "Demir", "Şahin", "Çelik", "Yıldız", "Aydın", "Öztürk"]},
    "AE": {"name": "United Arab Emirates", "phone_code": "+971", "phone_len": 9,
        "cities": [("Dubai", "DU", "00000"), ("Abu Dhabi", "AZ", "00001"), ("Sharjah", "SH", "00002")],
        "streets": ["Sheikh Zayed Road", "Jumeirah Beach Road", "Corniche Road"],
        "first": ["Mohammed", "Ahmed", "Ali", "Omar", "Khalid", "Saeed", "Sultan", "Hamdan"],
        "last": ["Al Maktoum", "Al Nahyan", "Al Falasi", "Al Suwaidi", "Al Mazrouei"]},
    "SA": {"name": "Saudi Arabia", "phone_code": "+966", "phone_len": 9,
        "cities": [("Riyadh", "Riyadh", "11564"), ("Jeddah", "Makkah", "21442"),
                   ("Dammam", "Eastern", "31411")],
        "streets": ["King Fahd Road", "Olaya Street", "Tahlia Street"],
        "first": ["Abdullah", "Mohammed", "Ahmed", "Faisal", "Khalid", "Saud"],
        "last": ["Al Saud", "Al Otaibi", "Al Qahtani", "Al Harbi", "Al Shehri"]},
    "QA": {"name": "Qatar", "phone_code": "+974", "phone_len": 8,
        "cities": [("Doha", "DA", "00000"), ("Al Rayyan", "RA", "00001")],
        "streets": ["Corniche Road", "Salwa Road", "Al Sadd Street"],
        "first": ["Mohammed", "Ahmed", "Khalid", "Abdullah", "Jassim", "Hamad"],
        "last": ["Al Thani", "Al Kuwari", "Al Mannai", "Al Emadi", "Al Marri"]},
    "KW": {"name": "Kuwait", "phone_code": "+965", "phone_len": 8,
        "cities": [("Kuwait City", "KU", "00000"), ("Hawalli", "HA", "00001")],
        "streets": ["Gulf Road", "Salem Al Mubarak Street", "Fahd Al Salem Street"],
        "first": ["Abdullah", "Mohammed", "Ahmed", "Fahad", "Khaled", "Yousef"],
        "last": ["Al Sabah", "Al Ahmad", "Al Mutairi", "Al Rashidi", "Al Azmi"]},
    "BH": {"name": "Bahrain", "phone_code": "+973", "phone_len": 8,
        "cities": [("Manama", "CP", "00000"), ("Riffa", "SO", "00001")],
        "streets": ["King Faisal Highway", "Palace Avenue", "Exhibition Road"],
        "first": ["Ahmed", "Mohammed", "Ali", "Hassan", "Khalid", "Yousef"],
        "last": ["Al Khalifa", "Al Doseri", "Al Zayani", "Al Ansari", "Al Mannai"]},
    "OM": {"name": "Oman", "phone_code": "+968", "phone_len": 8,
        "cities": [("Muscat", "MA", "00000"), ("Salalah", "DH", "00001")],
        "streets": ["Sultan Qaboos Street", "Al Qurum Street", "Al Khuwair Street"],
        "first": ["Ahmed", "Mohammed", "Ali", "Salim", "Said", "Khalid"],
        "last": ["Al Busaidi", "Al Said", "Al Habsi", "Al Balushi", "Al Rawahi"]},
    "JO": {"name": "Jordan", "phone_code": "+962", "phone_len": 9,
        "cities": [("Amman", "AM", "11110"), ("Zarqa", "AZ", "13110"), ("Irbid", "IR", "21110")],
        "streets": ["King Hussein Street", "Rainbow Street", "Madaba Street"],
        "first": ["Mohammed", "Ahmed", "Omar", "Ali", "Yousef", "Khalid"],
        "last": ["Al Abdullah", "Al Masri", "Al Khalidi", "Al Nabulsi", "Al Husseini"]},
    "LB": {"name": "Lebanon", "phone_code": "+961", "phone_len": 8,
        "cities": [("Beirut", "BA", "1107"), ("Tripoli", "AS", "1300"), ("Sidon", "JA", "1600")],
        "streets": ["Hamra Street", "Rue Gouraud", "Avenue Charles Malek"],
        "first": ["Mohammed", "Ali", "Georges", "Elie", "Hassan", "Nabil"],
        "last": ["Khoury", "Haddad", "Nassar", "Saad", "Fares", "Aoun"]},
    "IL": {"name": "Israel", "phone_code": "+972", "phone_len": 9,
        "cities": [("Tel Aviv", "TA", "61000"), ("Jerusalem", "JM", "91000"), ("Haifa", "HA", "31000")],
        "streets": ["Rothschild Boulevard", "Dizengoff Street", "Jaffa Road"],
        "first": ["David", "Yosef", "Moshe", "Aharon", "Yitzhak", "Shlomo"],
        "last": ["Cohen", "Levi", "Mizrahi", "Peretz", "Biton", "Dahan"]},
    "IR": {"name": "Iran", "phone_code": "+98", "phone_len": 10,
        "cities": [("Tehran", "THR", "11111111"), ("Mashhad", "RKH", "9176711111")],
        "streets": ["Valiasr Street", "Enghelab Street"],
        "first": ["Ali", "Reza", "Hassan", "Mohammad"],
        "last": ["Ahmadi", "Hosseini", "Mohammadi", "Rezaei"]},
    "IQ": {"name": "Iraq", "phone_code": "+964", "phone_len": 10,
        "cities": [("Baghdad", "BG", "10001"), ("Basra", "BA", "61001")],
        "streets": ["Al Rashid Street", "Al Karrada Street"],
        "first": ["Ahmed", "Ali", "Mohammed", "Hassan"],
        "last": ["Al Baghdadi", "Al Iraqi", "Al Jubouri", "Al Dulaimi"]},

    # ───────── AFRICA ─────────
    "ZA": {"name": "South Africa", "phone_code": "+27", "phone_len": 9,
        "cities": [("Johannesburg", "GP", "2001"), ("Cape Town", "WC", "8001"),
                   ("Durban", "KZN", "4001"), ("Pretoria", "GP", "0001")],
        "streets": ["Main Street", "Long Street", "Commissioner Street", "Church Street"],
        "first": ["Pieter", "Johan", "Thabo", "Sipho", "David", "Michael", "John", "Peter"],
        "last": ["Van der Merwe", "Botha", "Nkosi", "Dlamini", "Smith", "Jacobs", "Ndlovu", "Khumalo"]},
    "EG": {"name": "Egypt", "phone_code": "+20", "phone_len": 9,
        "cities": [("Cairo", "C", "11511"), ("Alexandria", "ALX", "21500"),
                   ("Giza", "GZ", "12511"), ("Luxor", "LX", "85511")],
        "streets": ["Talaat Harb Street", "Corniche El Nil", "Ramses Street"],
        "first": ["Mohamed", "Ahmed", "Mahmoud", "Ali", "Hassan", "Ibrahim"],
        "last": ["El Sayed", "Hassan", "Ibrahim", "Abdullah", "Mostafa"]},
    "MA": {"name": "Morocco", "phone_code": "+212", "phone_len": 9,
        "cities": [("Casablanca", "CAS", "20000"), ("Rabat", "RAB", "10000"),
                   ("Marrakech", "MRK", "40000"), ("Fes", "FES", "30000")],
        "streets": ["Avenue Mohammed V", "Boulevard Zerktouni", "Rue de la Liberté"],
        "first": ["Mohamed", "Youssef", "Ahmed", "Karim", "Hamza", "Reda"],
        "last": ["El Amrani", "Benali", "Alaoui", "El Idrissi", "Bennani"]},
    "DZ": {"name": "Algeria", "phone_code": "+213", "phone_len": 9,
        "cities": [("Alger", "ALG", "16000"), ("Oran", "ORN", "31000"), ("Constantine", "CST", "25000")],
        "streets": ["Rue Didouche Mourad", "Boulevard Zirout Youcef"],
        "first": ["Mohamed", "Ahmed", "Karim", "Yacine", "Bilal", "Amine"],
        "last": ["Benali", "Hamdani", "Bouzid", "Mansouri", "Belkacem"]},
    "TN": {"name": "Tunisia", "phone_code": "+216", "phone_len": 8,
        "cities": [("Tunis", "TUN", "1000"), ("Sfax", "SFX", "3000"), ("Sousse", "SUS", "4000")],
        "streets": ["Avenue Habib Bourguiba", "Rue de la Liberté"],
        "first": ["Mohamed", "Ahmed", "Karim", "Sami", "Amine"],
        "last": ["Ben Ali", "Trabelsi", "Bouazizi", "Hamdi", "Gharbi"]},
    "LY": {"name": "Libya", "phone_code": "+218", "phone_len": 9,
        "cities": [("Tripoli", "TB", "00218"), ("Benghazi", "BA", "00218")],
        "streets": ["Omar Al Mukhtar Street", "Independence Street"],
        "first": ["Mohamed", "Ahmed", "Ali", "Khalid"],
        "last": ["Al Gaddafi", "Al Senussi", "Al Warfalli", "Al Zawiya"]},
    "NG": {"name": "Nigeria", "phone_code": "+234", "phone_len": 10,
        "cities": [("Lagos", "LA", "100001"), ("Abuja", "FC", "900001"),
                   ("Kano", "KN", "700001"), ("Ibadan", "OY", "200001")],
        "streets": ["Broad Street", "Marina Road", "Awolowo Road", "Ahmadu Bello Way"],
        "first": ["Chinedu", "Emeka", "Adebayo", "Oluwaseun", "Ifeanyi", "Abdul"],
        "last": ["Okafor", "Adeyemi", "Okonkwo", "Balogun", "Eze", "Ibrahim"]},
    "KE": {"name": "Kenya", "phone_code": "+254", "phone_len": 9,
        "cities": [("Nairobi", "NRB", "00100"), ("Mombasa", "MSA", "80100"), ("Kisumu", "KSI", "40100")],
        "streets": ["Kenyatta Avenue", "Moi Avenue", "Tom Mboya Street"],
        "first": ["John", "Peter", "David", "James", "Michael", "Joseph"],
        "last": ["Mwangi", "Otieno", "Kamau", "Ochieng", "Njoroge", "Wanjiku"]},
    "GH": {"name": "Ghana", "phone_code": "+233", "phone_len": 9,
        "cities": [("Accra", "AA", "GA-001"), ("Kumasi", "AH", "AK-001")],
        "streets": ["Oxford Street", "Ring Road"],
        "first": ["Kwame", "Kofi", "Yaw", "Kwesi"],
        "last": ["Mensah", "Osei", "Boateng", "Asante"]},
    "ET": {"name": "Ethiopia", "phone_code": "+251", "phone_len": 9,
        "cities": [("Addis Ababa", "AA", "1000"), ("Dire Dawa", "DD", "3000")],
        "streets": ["Bole Road", "Churchill Avenue"],
        "first": ["Abebe", "Tesfaye", "Getachew", "Girma"],
        "last": ["Bekele", "Kebede", "Assefa", "Tesfaye"]},
    "TZ": {"name": "Tanzania", "phone_code": "+255", "phone_len": 9,
        "cities": [("Dar es Salaam", "DSM", "11101"), ("Dodoma", "DOD", "41101")],
        "streets": ["Samora Avenue", "Nyerere Road"],
        "first": ["Juma", "Hamisi", "Joseph", "Peter"],
        "last": ["Mwangi", "Kimani", "Ochieng", "Hassan"]},
    "UG": {"name": "Uganda", "phone_code": "+256", "phone_len": 9,
        "cities": [("Kampala", "KLA", "00001"), ("Entebbe", "ENT", "00002")],
        "streets": ["Kampala Road", "Entebbe Road"],
        "first": ["Moses", "David", "Peter", "John"],
        "last": ["Kato", "Ssebunya", "Mukasa", "Nsubuga"]},
    "ZW": {"name": "Zimbabwe", "phone_code": "+263", "phone_len": 9,
        "cities": [("Harare", "HA", "00001"), ("Bulawayo", "BU", "00002")],
        "streets": ["Samora Machel Avenue", "Julius Nyerere Way"],
        "first": ["Tendai", "Tinashe", "Farai", "Takudzwa"],
        "last": ["Moyo", "Ncube", "Sibanda", "Dube"]},
    "ZM": {"name": "Zambia", "phone_code": "+260", "phone_len": 9,
        "cities": [("Lusaka", "LK", "10101"), ("Kitwe", "CB", "50100")],
        "streets": ["Cairo Road", "Great East Road"],
        "first": ["Chanda", "Mwamba", "Bwalya", "Mulenga"],
        "last": ["Banda", "Phiri", "Zulu", "Mulenga"]},
    "SN": {"name": "Senegal", "phone_code": "+221", "phone_len": 9,
        "cities": [("Dakar", "DK", "10000"), ("Touba", "DB", "20000")],
        "streets": ["Avenue Léopold Sédar Senghor", "Rue Carnot"],
        "first": ["Mamadou", "Ousmane", "Ibrahima", "Cheikh"],
        "last": ["Diop", "Diallo", "Ndiaye", "Fall"]},
    "CI": {"name": "Ivory Coast", "phone_code": "+225", "phone_len": 10,
        "cities": [("Abidjan", "AB", "00000"), ("Yamoussoukro", "YM", "00001")],
        "streets": ["Boulevard de Marseille", "Avenue Chardy"],
        "first": ["Konan", "Kouassi", "Koffi", "Yao"],
        "last": ["Koné", "Traoré", "Diabaté", "Coulibaly"]},

    # ───────── ASIA ─────────
    "IN": {"name": "India", "phone_code": "+91", "phone_len": 10,
        "cities": [("Mumbai", "MH", "400001"), ("Delhi", "Delhi", "110001"),
                   ("Bangalore", "KA", "560001"), ("Chennai", "TN", "600001"),
                   ("Kolkata", "WB", "700001"), ("Hyderabad", "TS", "500001"),
                   ("Pune", "MH", "411001"), ("Ahmedabad", "GJ", "380001")],
        "streets": ["MG Road", "Nehru Road", "Gandhi Marg", "Linking Road",
                    "Park Street", "Brigade Road"],
        "first": ["Aarav", "Vivaan", "Aditya", "Vihaan", "Arjun", "Sai",
                  "Rohan", "Karan", "Rahul", "Amit"],
        "last": ["Sharma", "Verma", "Patel", "Kumar", "Singh", "Gupta",
                 "Reddy", "Nair", "Iyer", "Joshi"]},
    "PK": {"name": "Pakistan", "phone_code": "+92", "phone_len": 10,
        "cities": [("Karachi", "Sindh", "74000"), ("Lahore", "Punjab", "54000"),
                   ("Islamabad", "ICT", "44000"), ("Rawalpindi", "Punjab", "46000")],
        "streets": ["Main Boulevard", "Mall Road", "Jinnah Road"],
        "first": ["Muhammad", "Ahmed", "Ali", "Hassan", "Usman", "Bilal"],
        "last": ["Khan", "Ahmed", "Malik", "Sheikh", "Chaudhry", "Butt"]},
    "BD": {"name": "Bangladesh", "phone_code": "+880", "phone_len": 10,
        "cities": [("Dhaka", "DH", "1000"), ("Chittagong", "CG", "4000"), ("Khulna", "KH", "9000")],
        "streets": ["Gulshan Avenue", "Mirpur Road", "Dhanmondi Road"],
        "first": ["Abdul", "Mohammad", "Rahim", "Karim", "Hasan", "Rashid"],
        "last": ["Islam", "Hossain", "Ahmed", "Rahman", "Chowdhury", "Khan"]},
    "LK": {"name": "Sri Lanka", "phone_code": "+94", "phone_len": 9,
        "cities": [("Colombo", "WP", "00100"), ("Kandy", "CP", "20000"), ("Galle", "SP", "80000")],
        "streets": ["Galle Road", "Marine Drive", "Temple Road"],
        "first": ["Kasun", "Nuwan", "Chamara", "Dinesh", "Sampath", "Lahiru"],
        "last": ["Perera", "Silva", "Fernando", "Jayawardena", "Bandara", "Rajapaksa"]},
    "NP": {"name": "Nepal", "phone_code": "+977", "phone_len": 9,
        "cities": [("Kathmandu", "BA", "44600"), ("Pokhara", "GA", "33700")],
        "streets": ["Durbar Marg", "New Road", "Lazimpat"],
        "first": ["Ram", "Shyam", "Hari", "Bishnu", "Krishna", "Suresh"],
        "last": ["Sharma", "Thapa", "Gurung", "Magar", "Rai", "Limbu"]},
    "CN": {"name": "China", "phone_code": "+86", "phone_len": 11,
        "cities": [("Beijing", "BJ", "100000"), ("Shanghai", "SH", "200000"),
                   ("Guangzhou", "GD", "510000"), ("Shenzhen", "GD", "518000"),
                   ("Chengdu", "SC", "610000")],
        "streets": ["Nanjing Road", "Wangfujing Street", "Huaihai Road", "Changan Avenue"],
        "first": ["Wei", "Ming", "Hao", "Jun", "Lei", "Bo", "Chen", "Yang"],
        "last": ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhou"]},
    "HK": {"name": "Hong Kong", "phone_code": "+852", "phone_len": 8,
        "cities": [("Hong Kong", "HK", "000000"), ("Kowloon", "KL", "000001")],
        "streets": ["Nathan Road", "Queen's Road", "Des Voeux Road"],
        "first": ["Wei", "Ming", "Hao", "Jun", "Ka", "Chun"],
        "last": ["Chan", "Wong", "Lee", "Cheung", "Lau", "Ho"]},
    "TW": {"name": "Taiwan", "phone_code": "+886", "phone_len": 9,
        "cities": [("Taipei", "TPE", "100"), ("Kaohsiung", "KHH", "800"), ("Taichung", "TXG", "400")],
        "streets": ["Zhongxiao Road", "Xinyi Road", "Nanjing Road"],
        "first": ["Wei", "Ming", "Hao", "Jun", "Yi", "Cheng"],
        "last": ["Chen", "Lin", "Huang", "Chang", "Lee", "Wang"]},
    "JP": {"name": "Japan", "phone_code": "+81", "phone_len": 10,
        "cities": [("Tokyo", "13", "100-0001"), ("Osaka", "27", "530-0001"),
                   ("Kyoto", "26", "600-0001"), ("Nagoya", "23", "460-0001"),
                   ("Yokohama", "14", "220-0011")],
        "streets": ["Chuo-dori", "Omotesando", "Ginza", "Shinjuku-dori"],
        "first": ["Takashi", "Yuki", "Hiroshi", "Kenji", "Yuto", "Sota", "Haruto", "Ren"],
        "last": ["Yamamoto", "Tanaka", "Suzuki", "Takahashi", "Watanabe", "Ito", "Nakamura", "Kobayashi"]},
    "KR": {"name": "South Korea", "phone_code": "+82", "phone_len": 10,
        "cities": [("Seoul", "11", "03000"), ("Busan", "26", "48000"), ("Incheon", "28", "22000")],
        "streets": ["Gangnam-daero", "Teheran-ro", "Sejong-daero"],
        "first": ["Min-jun", "Ji-ho", "Seo-jun", "Do-yun", "Ye-jun", "Ha-jun"],
        "last": ["Kim", "Lee", "Park", "Choi", "Jung", "Kang"]},
    "TH": {"name": "Thailand", "phone_code": "+66", "phone_len": 9,
        "cities": [("Bangkok", "BKK", "10100"), ("Chiang Mai", "CMI", "50000"), ("Phuket", "HKT", "83000")],
        "streets": ["Sukhumvit Road", "Silom Road", "Khao San Road"],
        "first": ["Somchai", "Somsak", "Sombat", "Anan", "Chatchai", "Niran"],
        "last": ["Srisuwan", "Rattanakorn", "Wongchai", "Chaiyaporn", "Suwan"]},
    "VN": {"name": "Vietnam", "phone_code": "+84", "phone_len": 9,
        "cities": [("Hà Nội", "HN", "100000"), ("Hồ Chí Minh", "SG", "700000"), ("Đà Nẵng", "DN", "500000")],
        "streets": ["Nguyễn Huệ", "Lê Lợi", "Trần Hưng Đạo"],
        "first": ["An", "Bình", "Cường", "Dũng", "Hải", "Hùng"],
        "last": ["Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh"]},
    "PH": {"name": "Philippines", "phone_code": "+63", "phone_len": 10,
        "cities": [("Manila", "NCR", "1000"), ("Quezon City", "NCR", "1100"), ("Cebu City", "CEB", "6000")],
        "streets": ["Rizal Avenue", "EDSA", "Ayala Avenue"],
        "first": ["Juan", "Jose", "Pedro", "Miguel", "Rafael", "Carlos"],
        "last": ["Santos", "Reyes", "Cruz", "Garcia", "Bautista", "Mendoza"]},
    "MY": {"name": "Malaysia", "phone_code": "+60", "phone_len": 9,
        "cities": [("Kuala Lumpur", "KL", "50000"), ("Penang", "PG", "10000"),
                   ("Johor Bahru", "JH", "80000")],
        "streets": ["Jalan Bukit Bintang", "Jalan Ampang", "Jalan Sultan Ismail"],
        "first": ["Ahmad", "Mohammed", "Lee", "Tan", "Raj", "Kumar"],
        "last": ["Abdullah", "Rahman", "Tan", "Lim", "Lee", "Wong"]},
    "SG": {"name": "Singapore", "phone_code": "+65", "phone_len": 8,
        "cities": [("Singapore", "SG", "018956"), ("Jurong", "SG", "609498")],
        "streets": ["Orchard Road", "Raffles Place", "Marina Bay Sands"],
        "first": ["Wei", "Ming", "Hao", "Jun", "Jia", "Xin"],
        "last": ["Tan", "Lim", "Lee", "Ng", "Wong", "Chua"]},
    "ID": {"name": "Indonesia", "phone_code": "+62", "phone_len": 10,
        "cities": [("Jakarta", "JK", "10110"), ("Surabaya", "JI", "60111"),
                   ("Bandung", "JB", "40111"), ("Medan", "SU", "20111")],
        "streets": ["Jalan Sudirman", "Jalan Thamrin", "Jalan Gatot Subroto"],
        "first": ["Budi", "Agus", "Andi", "Rudi", "Dedi", "Eko"],
        "last": ["Santoso", "Wijaya", "Suharto", "Hartono", "Kusuma"]},
    "KZ": {"name": "Kazakhstan", "phone_code": "+7", "phone_len": 10,
        "cities": [("Almaty", "AL", "050000"), ("Astana", "AS", "010000")],
        "streets": ["Abay Avenue", "Dostyk Avenue"],
        "first": ["Nurlan", "Askar", "Yerlan", "Timur"],
        "last": ["Nazarbayev", "Tokayev", "Sultanov", "Iskakov"]},
    "UZ": {"name": "Uzbekistan", "phone_code": "+998", "phone_len": 9,
        "cities": [("Tashkent", "TK", "100000"), ("Samarkand", "SA", "140100")],
        "streets": ["Amir Temur Avenue", "Navoi Street"],
        "first": ["Aziz", "Bekzod", "Jasur", "Sherzod"],
        "last": ["Karimov", "Rakhimov", "Ismailov", "Yusupov"]},

    # ───────── OCEANIA ─────────
    "AU": {"name": "Australia", "phone_code": "+61", "phone_len": 9,
        "cities": [("Sydney", "NSW", "2000"), ("Melbourne", "VIC", "3000"),
                   ("Brisbane", "QLD", "4000"), ("Perth", "WA", "6000"),
                   ("Adelaide", "SA", "5000"), ("Canberra", "ACT", "2600")],
        "streets": ["George St", "Collins St", "Queen St", "King St",
                    "Elizabeth St", "Bourke St"],
        "first": ["Oliver", "Jack", "William", "Noah", "Thomas", "Henry",
                  "Lucas", "Cooper", "Liam", "Ethan"],
        "last": ["Smith", "Jones", "Williams", "Brown", "Wilson", "Taylor",
                 "Nguyen", "Martin", "Anderson", "Thomas"]},
    "NZ": {"name": "New Zealand", "phone_code": "+64", "phone_len": 9,
        "cities": [("Auckland", "AUK", "1010"), ("Wellington", "WGN", "6011"),
                   ("Christchurch", "CAN", "8011"), ("Hamilton", "WKO", "3200")],
        "streets": ["Queen St", "Lambton Quay", "Riccarton Road", "Victoria St"],
        "first": ["Jack", "Oliver", "William", "Liam", "Noah", "Hunter"],
        "last": ["Smith", "Wilson", "Brown", "Taylor", "Thompson", "Williams"]},
    "FJ": {"name": "Fiji", "phone_code": "+679", "phone_len": 7,
        "cities": [("Suva", "C", "0000"), ("Nadi", "W", "0000")],
        "streets": ["Victoria Parade", "Queen Elizabeth Drive"],
        "first": ["Semi", "Ratu", "Josaia", "Epeli", "Ilaisa"],
        "last": ["Naitasiri", "Cakobau", "Rabuka", "Vakatora"]},

    # ───────── CARIBBEAN ─────────
    "JM": {"name": "Jamaica", "phone_code": "+1876", "phone_len": 10,
        "cities": [("Kingston", "KIN", "JM-KIN"), ("Montego Bay", "MB", "JM-MB")],
        "streets": ["King Street", "Constant Spring Road"],
        "first": ["Andre", "Christopher", "Dwayne", "Michael"],
        "last": ["Brown", "Williams", "Johnson", "Smith"]},
    "TT": {"name": "Trinidad and Tobago", "phone_code": "+1868", "phone_len": 10,
        "cities": [("Port of Spain", "POS", "TT-POS"), ("San Fernando", "SF", "TT-SF")],
        "streets": ["Frederick Street", "Independence Square"],
        "first": ["Kareem", "Jason", "Marcus", "Dwayne"],
        "last": ["Williams", "Joseph", "Singh", "Ramnarine"]},
    "BS": {"name": "Bahamas", "phone_code": "+1242", "phone_len": 10,
        "cities": [("Nassau", "NP", "BS-NP"), ("Freeport", "FP", "BS-FP")],
        "streets": ["Bay Street", "Shirley Street"],
        "first": ["Marcus", "Kevin", "Shaquille", "Dwayne"],
        "last": ["Rolle", "Bain", "Saunders", "Ferguson"]},
    "BB": {"name": "Barbados", "phone_code": "+1246", "phone_len": 10,
        "cities": [("Bridgetown", "ST", "BB-ST"), ("Speightstown", "ST", "BB-ST")],
        "streets": ["Broad Street", "Swan Street"],
        "first": ["Andre", "Dwayne", "Jamal", "Marcus"],
        "last": ["Clarke", "Browne", "Greenidge", "Holder"]},
    "GY": {"name": "Guyana", "phone_code": "+592", "phone_len": 7,
        "cities": [("Georgetown", "DE", "GY-DE"), ("Linden", "UP", "GY-UP")],
        "streets": ["Main Street", "Regent Street"],
        "first": ["Ramesh", "Kevin", "Dwayne", "Vishal"],
        "last": ["Singh", "Williams", "Persaud", "Rampersad"]},

    # ───────── CENTRAL AMERICA ─────────
    "GT": {"name": "Guatemala", "phone_code": "+502", "phone_len": 8,
        "cities": [("Ciudad de Guatemala", "GU", "01001"), ("Quetzaltenango", "QZ", "09001")],
        "streets": ["Avenida Reforma", "Calzada Roosevelt"],
        "first": ["Carlos", "José", "Luis", "Miguel"],
        "last": ["García", "Rodríguez", "López", "Pérez"]},
    "CR": {"name": "Costa Rica", "phone_code": "+506", "phone_len": 8,
        "cities": [("San José", "SJ", "10101"), ("Alajuela", "AL", "20101")],
        "streets": ["Avenida Central", "Calle Central"],
        "first": ["José", "Carlos", "Luis", "Miguel"],
        "last": ["Rodríguez", "González", "Pérez", "Mora"]},
    "PA": {"name": "Panama", "phone_code": "+507", "phone_len": 8,
        "cities": [("Panama City", "8", "0801"), ("Colón", "3", "0301")],
        "streets": ["Avenida Balboa", "Calle 50"],
        "first": ["José", "Carlos", "Luis", "Ricardo"],
        "last": ["Rodríguez", "González", "Pérez", "Martínez"]},
    "HN": {"name": "Honduras", "phone_code": "+504", "phone_len": 8,
        "cities": [("Tegucigalpa", "FM", "11101"), ("San Pedro Sula", "CR", "21101")],
        "streets": ["Boulevard Morazán", "Avenida Juan Pablo II"],
        "first": ["Carlos", "José", "Luis", "Miguel"],
        "last": ["Hernández", "López", "García", "Martínez"]},
    "SV": {"name": "El Salvador", "phone_code": "+503", "phone_len": 8,
        "cities": [("San Salvador", "SS", "1101"), ("Santa Ana", "SA", "0201")],
        "streets": ["Alameda Roosevelt", "Boulevard de los Héroes"],
        "first": ["José", "Carlos", "Luis", "Miguel"],
        "last": ["Martínez", "López", "García", "Hernández"]},
    "NI": {"name": "Nicaragua", "phone_code": "+505", "phone_len": 8,
        "cities": [("Managua", "MN", "11001"), ("León", "LE", "21001")],
        "streets": ["Avenida Bolívar", "Calle Colón"],
        "first": ["José", "Carlos", "Luis", "Miguel"],
        "last": ["López", "Martínez", "García", "Hernández"]},
    "BZ": {"name": "Belize", "phone_code": "+501", "phone_len": 7,
        "cities": [("Belize City", "BZ", "00000"), ("Belmopan", "CY", "00001")],
        "streets": ["Albert Street", "Queen Street"],
        "first": ["John", "Michael", "David", "Robert"],
        "last": ["Smith", "Jones", "Williams", "Brown"]},

    # ───────── OTHERS ─────────
    "GE": {"name": "Georgia", "phone_code": "+995", "phone_len": 9,
        "cities": [("Tbilisi", "TB", "0100"), ("Batumi", "AJ", "6000")],
        "streets": ["Rustaveli Avenue", "Chavchavadze Avenue"],
        "first": ["Giorgi", "Nikoloz", "David", "Levan"],
        "last": ["Beridze", "Kapanadze", "Gelashvili", "Maisuradze"]},
    "AM": {"name": "Armenia", "phone_code": "+374", "phone_len": 8,
        "cities": [("Yerevan", "ER", "0001"), ("Gyumri", "SH", "3101")],
        "streets": ["Mashtots Avenue", "Baghramyan Avenue"],
        "first": ["Armen", "Hayk", "Vahan", "Tigran"],
        "last": ["Petrosyan", "Hakobyan", "Sargsyan", "Grigoryan"]},
    "AZ": {"name": "Azerbaijan", "phone_code": "+994", "phone_len": 9,
        "cities": [("Baku", "BA", "AZ1000"), ("Ganja", "GA", "AZ2000")],
        "streets": ["Nizami Street", "Fountain Square"],
        "first": ["Elvin", "Rashad", "Orkhan", "Kamran"],
        "last": ["Mammadov", "Aliyev", "Huseynov", "Hasanov"]},
    "MN": {"name": "Mongolia", "phone_code": "+976", "phone_len": 8,
        "cities": [("Ulaanbaatar", "1", "210000"), ("Erdenet", "2", "310000")],
        "streets": ["Peace Avenue", "Chinggis Avenue"],
        "first": ["Bat-Erdene", "Temujin", "Ganbold", "Bold"],
        "last": ["Batbayar", "Erdenebat", "Enkhbold", "Ganbaatar"]},
    "KH": {"name": "Cambodia", "phone_code": "+855", "phone_len": 9,
        "cities": [("Phnom Penh", "PP", "120000"), ("Siem Reap", "SR", "170000")],
        "streets": ["Monivong Boulevard", "Sisowath Quay"],
        "first": ["Sokha", "Chanthou", "Dara", "Rithy"],
        "last": ["Sok", "Chan", "Kim", "Chea"]},
    "LA": {"name": "Laos", "phone_code": "+856", "phone_len": 9,
        "cities": [("Vientiane", "VT", "01000"), ("Luang Prabang", "LP", "06000")],
        "streets": ["Samsenthai Road", "Setthathirath Road"],
        "first": ["Kham", "Boun", "Somsak", "Souvannavong"],
        "last": ["Phommasone", "Sisavath", "Inthavong", "Vongsa"]},
    "MM": {"name": "Myanmar", "phone_code": "+95", "phone_len": 9,
        "cities": [("Yangon", "YG", "11011"), ("Mandalay", "MD", "05011")],
        "streets": ["Sule Pagoda Road", "Anawrahta Road"],
        "first": ["Aung", "Kyaw", "Min", "Thura"],
        "last": ["Myint", "Win", "Htun", "Naing"]},
    "BT": {"name": "Bhutan", "phone_code": "+975", "phone_len": 8,
        "cities": [("Thimphu", "TT", "11001"), ("Paro", "PR", "12001")],
        "streets": ["Norzin Lam", "Chorten Lam"],
        "first": ["Tenzin", "Kinley", "Ugyen", "Sonam"],
        "last": ["Wangchuk", "Dorji", "Tshering", "Namgyel"]},
    "MV": {"name": "Maldives", "phone_code": "+960", "phone_len": 7,
        "cities": [("Malé", "MLE", "20001"), ("Addu City", "ADU", "19001")],
        "streets": ["Boduthakurufaanu Magu", "Ameer Ahmed Magu"],
        "first": ["Mohamed", "Ahmed", "Hassan", "Ibrahim"],
        "last": ["Rasheed", "Latheef", "Naseer", "Waheed"]},
}


# ───────────── PHONE FORMATTER ─────────────
def _fake_phone(code: str) -> str:
    """Generate realistic phone number for a country."""
    d = FAKE_DATA[code]
    n = d["phone_len"]

    # US/CA special format: (XXX) XXX-XXXX
    if code in ("US", "CA"):
        area = f"({random.randint(200, 999)})"
        mid = random.randint(200, 999)
        last = random.randint(1000, 9999)
        return f"{area} {mid}-{last}"

    # UK special format
    if code == "GB":
        return f"+44 {random.randint(1000, 9999)} {random.randint(100000, 999999)}"

    # Generic international format
    digits = "".join(str(random.randint(0, 9)) for _ in range(n))
    return f"{d['phone_code']} {digits}"


# ───────────── GET FAKE IDENTITY ─────────────
def get_fake(code: str = "US") -> dict:
    """
    Returns a full fake identity for a country.
    Returns None if country code is not found.
    """
    code = (code or "US").upper()

    if code not in FAKE_DATA:
        return None

    d = FAKE_DATA[code]
    first = random.choice(d["first"])
    last = random.choice(d["last"])
    street = f"{random.choice(d['streets'])} {random.randint(1, 9999)}"
    city, state, zip_c = random.choice(d["cities"])
    phone = _fake_phone(code)

    return {
        "name":         f"{first} {last}",
        "first":        first,
        "last":         last,
        "street":       street,
        "city":         city,
        "state":        state,
        "zip":          zip_c,
        "country":      d["name"],
        "country_code": code,
        "phone":        phone,
    }


# ───────────── HELPERS ─────────────
def all_country_codes() -> list:
    """Return sorted list of all country codes."""
    return sorted(FAKE_DATA.keys())


def country_count() -> int:
    """Return total number of countries."""
    return len(FAKE_DATA)


def country_name(code: str) -> str:
    """Return the full country name for a code, or None."""
    code = (code or "").upper()
    return FAKE_DATA.get(code, {}).get("name")